import { UserRole } from './roles.js';

export enum Permission {
  // Worker discovery & profiles
  SEARCH_WORKERS = 'SEARCH_WORKERS',
  VIEW_WORKER = 'VIEW_WORKER',
  UPDATE_WORKER_PROFILE = 'UPDATE_WORKER_PROFILE',
  UPDATE_WORKER_AVAILABILITY = 'UPDATE_WORKER_AVAILABILITY',
  UPLOAD_WORKER_DOCUMENT = 'UPLOAD_WORKER_DOCUMENT',

  // Bookings
  CREATE_BOOKING = 'CREATE_BOOKING',
  VIEW_BOOKING = 'VIEW_BOOKING',
  CANCEL_BOOKING = 'CANCEL_BOOKING',
  ACCEPT_BOOKING = 'ACCEPT_BOOKING',
  REJECT_BOOKING = 'REJECT_BOOKING',
  START_BOOKING = 'START_BOOKING',
  MARK_ARRIVED = 'MARK_ARRIVED',
  COMPLETE_BOOKING = 'COMPLETE_BOOKING',

  // Jobs
  CREATE_JOB = 'CREATE_JOB',
  VIEW_JOB = 'VIEW_JOB',
  SEARCH_JOBS = 'SEARCH_JOBS',
  APPLY_JOB = 'APPLY_JOB',
  MANAGE_APPLICATIONS = 'MANAGE_APPLICATIONS',

  // Reviews
  CREATE_REVIEW = 'CREATE_REVIEW',
  VIEW_REVIEWS = 'VIEW_REVIEWS',

  // Location & Routing
  GET_ROUTE = 'GET_ROUTE',
  GET_DISTANCE = 'GET_DISTANCE',

  // Notifications
  VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS',
  MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ',

  // Admin
  ADMIN_VIEW_DASHBOARD = 'ADMIN_VIEW_DASHBOARD',
  ADMIN_VIEW_PENDING_WORKERS = 'ADMIN_VIEW_PENDING_WORKERS',
  ADMIN_APPROVE_WORKER = 'ADMIN_APPROVE_WORKER',
  ADMIN_REJECT_WORKER = 'ADMIN_REJECT_WORKER',
  ADMIN_SUSPEND_USER = 'ADMIN_SUSPEND_USER',
  ADMIN_VERIFY_DOCUMENT = 'ADMIN_VERIFY_DOCUMENT',
  ADMIN_VIEW_AUDIT_LOGS = 'ADMIN_VIEW_AUDIT_LOGS',
}

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.CLIENT]: [
    Permission.SEARCH_WORKERS,
    Permission.VIEW_WORKER,
    Permission.CREATE_BOOKING,
    Permission.VIEW_BOOKING,
    Permission.CANCEL_BOOKING,
    Permission.CREATE_JOB,
    Permission.VIEW_JOB,
    Permission.SEARCH_JOBS,
    Permission.MANAGE_APPLICATIONS,
    Permission.CREATE_REVIEW,
    Permission.VIEW_REVIEWS,
    Permission.GET_ROUTE,
    Permission.GET_DISTANCE,
    Permission.VIEW_NOTIFICATIONS,
    Permission.MARK_NOTIFICATION_READ,
  ],
  [UserRole.WORKER]: [
    Permission.VIEW_WORKER,
    Permission.UPDATE_WORKER_PROFILE,
    Permission.UPDATE_WORKER_AVAILABILITY,
    Permission.UPLOAD_WORKER_DOCUMENT,
    Permission.VIEW_BOOKING,
    Permission.ACCEPT_BOOKING,
    Permission.REJECT_BOOKING,
    Permission.CANCEL_BOOKING,
    Permission.START_BOOKING,
    Permission.MARK_ARRIVED,
    Permission.COMPLETE_BOOKING,
    Permission.VIEW_JOB,
    Permission.SEARCH_JOBS,
    Permission.APPLY_JOB,
    Permission.CREATE_REVIEW,
    Permission.VIEW_REVIEWS,
    Permission.GET_ROUTE,
    Permission.GET_DISTANCE,
    Permission.VIEW_NOTIFICATIONS,
    Permission.MARK_NOTIFICATION_READ,
  ],
  [UserRole.ADMIN]: Object.values(Permission),
};
